const infojson = [
  {
    "timestamp": "5/3/2020 18:32:23",
    "email": "1705294@kiit.ac.in",
    "name": "Arpan Mukherjee",
    "crazy_things": "Prefer books borrowed from library more than own books, Linux is my religion. Liked writing \"shutdown now\" in .bashrc files in lab. ",
    "interests": "Was serious about being a musician until 2nd year, now like playing guitar to myself more. Like learning new tech stacks, like making everything one command away.",
    "post_lockdown_plan": "Go back to college, basically elope from home.",
    "insta": "",
    "more_info": "I love building teams and working with people meaningfully. That was the reason I started a small startup at KIIT which writes software for some B2B services. Checkout my team at vulmiqi.com",
    "about_mod": "Patience he has! Never seen him pissed off yet.",
    "oslo_bio": "This group's gonna rock anyway!",
    "highradius_exp": "First time full week in a row I am waking up in the morning and sleeping at night without being insomniac.",
    "pic": "https://drive.google.com/open?id=1krCE0Eq2or759rPzakT3R3yR_vhYRHUs",
    "skills": "Web Development, Automation Scripting, JavaScript ES6, Node.js, React, TypeScript, PostgreSQL, MongoDB, Django, Flutter, Python 3",
    "team": "WEB",
    "img_link": "https://i.ibb.co/n60kdkt/Whats-App-Image-2020-05-03-at-9-56-03-PM.jpg"
  },
  {
    "timestamp": "5/3/2020 10:37:30",
    "email": "1705514@kiit.ac.in",
    "name": "Prabhas Mondal",
    "crazy_things": "So I deal with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    "interests": "Make Websites and sometime Sleeping",
    "post_lockdown_plan": "Meet my closed ones.",
    "insta": "https://www.instagram.com/graduating_bulb_01_apr/",
    "more_info": "Wish to have an Royal Enfield HIMALYAN and want to do a K2K ride",
    "about_mod": "HospitableHamid.\nHe is generous or favorable towards quests; open-minded; receptive. Helping us a lot with 24hrs doubt clearing support.",
    "oslo_bio": "So, here comes our group....frankly speaking the member are very helpful. In spite of this virtual situation, we are communicating through various platforms which I think is quite good. I think our strong point is that we are performing as a group in spite of this work-from-home situation.",
    "highradius_exp": "A big change in my life is that before High Radius it like getting up from the bed, the whole day surfing the internet, and going back to bed. But now it's like getting up from bed, going through High Radius schedule, seeing Videos, working on Hands-On, Quiz, Assignment, and then go to bed again. In the middle food is the necessary part.",
    "pic": "https://drive.google.com/open?id=1rI3fYWfXgnUMqHWBvg564ALvU8wsIs7v",
    "skills": "Web Development, Android App Development",
    "team": "WEB",
    "img_link": "https://i.ibb.co/h8WyVJB/IMG-20190210-WA0024copy-PRABHAS-MONDAL.jpg"
  },
  {
    "timestamp": "5/3/2020 17:01:08",
    "email": "1706058@kiit.ac.in",
    "name": "Nishantika Auddy",
    "crazy_things": "I am the laziest person I know and I am usually too quiet until I get to know someone and then I can't shut up. I love eating so much that I learned to cook because of it. And I am a tiny bit OCD.",
    "interests": "Yes I definitely love sleeping and Netflix but I also love reading books and I usually have one ebook or another open on my phone always. ",
    "post_lockdown_plan": "Meet my friends. Go outside and eat all the street food I can get",
    "insta": "https://www.instagram.com/auddy_nish",
    "more_info": "",
    "about_mod": "He's a pretty cool guy and he helps out a lot!",
    "oslo_bio": "I think Oslo is full of inquisitive, super intelligent and most importantly helpful people",
    "highradius_exp": "It's been a crazy ride rushing to complete the videos on time so we could give the quizzes and then rushing to complete the assignments. But it's also been fun, refreshing and we are all gonna come out of this having learnt a LOT. And hopefully having made a few new friends!\nChanges I noticed in myself was that I usually tend to procrastinate but this time I was working hard and focused. The topics are super interesting and the hands on sessions require all our focus.\nCan't wait for week 2!",
    "pic": "https://drive.google.com/open?id=1LXbUrHp_sru6XZ4xH5jJmrIWz3EuF1JE",
    "skills": "Web development and android.\nMost proficient in Java.",
    "team": "WEB",
    "img_link": "https://i.ibb.co/rbhSLPc/IMG-20200129-160914-256-NISHANTIKA-AUDDY.jpg"
  },
  {
    "timestamp": "5/3/2020 1:18:56",
    "email": "1707289@kiit.ac.in",
    "name": "Meghadri Basu",
    "crazy_things": "I can waste an entire day doing nothing xD. I love boiled eggs but i hate omlettes. Ain't that crazy?",
    "interests": "Sleeping is definitely what i like to do the most, but we aren't getting much sleep of late, are we?  XD",
    "post_lockdown_plan": "Go out and eat my favourite Chillies burger.",
    "insta": "https://www.instagram.com/meghadri_basu",
    "more_info": "",
    "about_mod": "Hamid is very helpful and supportive. Definitely wants us to outperform ourselves and give our best.",
    "oslo_bio": "Oslo , so far has been great. We have a very good housemates who are always ready to help each other all the time.",
    "highradius_exp": "Learned a lot since Day 1. Definitely got to know myself a lot better in this 1 week of rigorous training.",
    "pic": "https://drive.google.com/open?id=1kgZvcFWoHFUvnMKLwqmFQpkNovQe3uNy",
    "skills": "A good team player,highly motivated individual, hardworking",
    "team": "",
    "img_link": "https://i.ibb.co/2NZ5HGT/Pics-Art-12-25-02-58-40-MEGHADRI-BASU.jpg"
  },
  {
    "timestamp": "5/3/2020 1:19:34",
    "email": "1706329@kiit.ac.in",
    "name": "Kalpana Grewal",
    "crazy_things": "I am funny but i am short tempered person.   ",
    "interests": "I really loved to watch series and movies. And sleeping.. I love to do photography.",
    "post_lockdown_plan": "Go and eat street foods,pizza and burger.. And gonna spend some time with my friends",
    "insta": "https://www.instagram.com/kalpanagrewal",
    "more_info": "",
    "about_mod": "He is sweet and very helpful. ",
    "oslo_bio": "I think there is good interaction and good environment ",
    "highradius_exp": "After joining  i learnt about the time management.. Someday it's feel too much hectic but i enjoyed a lot. ",
    "pic": "https://drive.google.com/open?id=1AYmOft756mh81Xxz90sDnbUbgqVeVHAv",
    "skills": "Photographer,Quick-learner,management skills",
    "team": "MEDIA",
    "img_link": "https://i.ibb.co/NsWvPLz/IMG-20200116-WA0000-KALPANA-GREWAL.jpg"
  },
  {
    "timestamp": "5/3/2020 1:20:09",
    "email": "1705789@kiit.ac.in",
    "name": "Himanshu Narayan Kalundia",
    "crazy_things": "I sleep too early at night, my friends say that",
    "interests": "Gaming, workout",
    "post_lockdown_plan": "Go to park and jog...maybe or hanging out with friends at Dominos",
    "insta": "",
    "more_info": "",
    "about_mod": "Don't you dare call him sir, just Hamid",
    "oslo_bio": "Oslo is a cute name",
    "highradius_exp": "It's a new kind of environment. I hope, soon I'll get used to it.",
    "pic": "https://drive.google.com/open?id=1dzQKGNjNnzgtgcD6hH-5g4ual8_DrPxz",
    "skills": "Unity 3D Engine",
    "team": "",
    "img_link": "https://i.ibb.co/T2LmWg8/PSX-20200110-234122-2-HIMANSHU-NARAYAN-KALUNDIA.jpg"
  },
  {
    "timestamp": "5/3/2020 1:21:51",
    "email": "1705746@kiit.ac.in",
    "name": "Sourabh Garg",
    "crazy_things": "Bunking lectures ",
    "interests": "Exploring on YouTube ",
    "post_lockdown_plan": "Would like to meet my friends ",
    "insta": "https://www.instagram.com/sourabhh_garg ",
    "more_info": "",
    "about_mod": "Very cooperative ",
    "oslo_bio": "Calm and body builder",
    "highradius_exp": "Very high pace . Just breakdown",
    "pic": "https://drive.google.com/open?id=1g8YUd185SDp-fwANZ-J0W7IWuZull9QO",
    "skills": "",
    "team": "WEB",
    "img_link": "https://i.ibb.co/34zTdNm/FB-IMG-1588448180418-sourabh-garg.jpg"
  },
  {
    "timestamp": "5/3/2020 17:01:28",
    "email": "1705950@kiit.ac.in",
    "name": "Sayanta Mukherjee",
    "crazy_things": "Still don't know how to make a cup of coffee.",
    "interests": "play computer games and cricket",
    "post_lockdown_plan": "Have my favorite foods",
    "insta": "",
    "more_info": "",
    "about_mod": "Don't like being called as sir",
    "oslo_bio": "As Oslo (capital of norway) is known for its green spaces and museum, in the same way our oslo group is a part of our green life with  love, friendship and efforts which will never be forgotten",
    "highradius_exp": "It gives the taste of corporate world. Though its just 1 week, still got to learn new skills as well as upgrade the older ones. Most importantly i am now able to maintain my time more efficiently.",
    "pic": "https://drive.google.com/open?id=1J5bS8fAVw6VDdVDDDTfyBI88b80qJiay",
    "skills": "c,c++,python,machine learning,mysql",
    "team": "",
    "img_link": "https://i.ibb.co/Jsf60KF/Screenshot-2019-03-16-23-56-04-742-Sayanta-Mukherjee.png"
  },
  {
    "timestamp": "5/3/2020 1:30:12",
    "email": "1706593@kiit.ac.in",
    "name": "Amit Kumar",
    "crazy_things": "I'm a big foodie and passionate about coding and gaming.",
    "interests": "I love to sleep with peace when i have a tiring day.",
    "post_lockdown_plan": "I'll go for a long bike ride.",
    "insta": "",
    "more_info": "",
    "about_mod": "He's helpful and talks to the point.",
    "oslo_bio": "House Oslo has best members among all and even better moderator. We are going to have a great time together.",
    "highradius_exp": "My experience at HighWay to HighRadius is pretty good. As we have a time assigned for every topics or quiz and deadline for every assignment, the major time of the day is spent in learning and\nI'm able to learn more in less time.     ",
    "pic": "https://drive.google.com/open?id=1mjifQbRiSb6S3w913TMpYclxkGabgkjx",
    "skills": "Problem solving, Abstract thinking, Critical thinking, adaptability",
    "team": "",
    "img_link": "https://i.ibb.co/26Q4Z9x/1-Profile-pic-Amit-Kumar.jpg"
  },
  {
    "timestamp": "5/3/2020 1:30:31",
    "email": "1704360@kiit.ac.in",
    "name": "Lavesh Gaurav",
    "crazy_things": "Even i don't know \ud83d\ude02",
    "interests": "Gaming, Blog Reading. ",
    "post_lockdown_plan": "Long drive.",
    "insta": "https://www.instagram.com/gaurav_lavesh",
    "more_info": "Hobbies: Photography.",
    "about_mod": "He's too calm and composed, can't imagine a teacher clearing doubts of 5-6 student so calmly. ",
    "oslo_bio": "Calm and destructive. ",
    "highradius_exp": "Ability to sit for hours without break increased. ",
    "pic": "https://drive.google.com/open?id=1jMMReAt4p1XOB1ZjTTDTm9xZORAo9wjZ",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 1:33:23",
    "email": "1704084@kiit.ac.in",
    "name": "Abhranil ",
    "crazy_things": "I don't know",
    "interests": "Sleeping ",
    "post_lockdown_plan": "Obviously bike riding.",
    "insta": "",
    "more_info": "",
    "about_mod": "Cool and helpful",
    "oslo_bio": "Capital of Norway!!!",
    "highradius_exp": "Interesting and hectic life",
    "pic": "https://drive.google.com/open?id=1mn2pISpOn5JsVemrLvPereRFc2AyJ7Fn",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 17:28:51",
    "email": "1706279@kiit.ac.in",
    "name": "Utkarsh Sinha",
    "crazy_things": "What crazy things?Does this involve intentionally sharing controversial posts on facebook to offend some people and have a long debate on that.By any chance does it sound crazy to you that sometimes I may wake up till 6 in the morning",
    "interests": "Quizzing and binge watching at the moment.\nA big dan brown fan by the way.",
    "post_lockdown_plan": "Get a hair cut\ud83d\ude02On a serious note,first I wil lsatisfy my cravings for shwarma and biryani",
    "insta": "https://www.instagram.com/utkarshsinha_11",
    "more_info": "",
    "about_mod": "Mereko sir nahi but hamid bulane ka.\ud83d\ude1b\nHe is a pretty cool guy by the way and always emphasises on the fact that we get answers to our doubts.\n",
    "oslo_bio": "Slowly getting to know each other now.\nA bunch of talented and hard working individuals in the group who are ready for hustle.",
    "highradius_exp": "Well for starters I stopped binge watching.So, a big win win situation there.\nThis internship has given me a chance to explore things and areas which remained unexplored till now.Have started using time in the lockdown period a bit better than before.",
    "pic": "https://drive.google.com/open?id=1xeYrINleoTQhuAx9_ExbexKgho6_UcW2",
    "skills": "Skilled in android studio and Adobe xd.\nAlso I love to code.",
    "team": "",
    "img_link": "https://i.ibb.co/LNH6BSW/20200329-143343-UTKARSH-SINHA.jpg"
  },
  {
    "timestamp": "5/3/2020 1:59:23",
    "email": "1706108@kiit.ac.in",
    "name": "AMAR",
    "crazy_things": "I am from DELHI #$*#&#",
    "interests": "I like to do ultra bakwaas RAP",
    "post_lockdown_plan": "HighRadius tour and Street Food",
    "insta": "https://www.instagram.com/amarbilal123/",
    "more_info": "Hahaha there is nothing to say ..just practice otherwise you are out the race",
    "about_mod": "He is a interesting No Bakwaas Work type of guy",
    "oslo_bio": "It's sucking but now part of my daily routine.",
    "highradius_exp": "HighRadius will make you diamonds from coal",
    "pic": "https://drive.google.com/open?id=1A-bwIg9Y-5o70YpYjjxDa2i03loUpd4C",
    "skills": "",
    "team": "MEDIA",
    "img_link": "https://i.ibb.co/d56MM0s/IMG-20200503-015454-AMAR.jpg"
  },
  {
    "timestamp": "5/3/2020 17:39:24",
    "email": "1707254@kiit.ac.in",
    "name": "Akriti Dey",
    "crazy_things": "An introvert when you don't know me and far too extrovert when you know me",
    "interests": "Drawing / Painting",
    "post_lockdown_plan": "Will have a large pizza or momos, burgers or any street food and also catch-up to my bestest buddies",
    "insta": "https://www.instagram.com/akriti._.dey",
    "more_info": "A cosmos lover and loves cooking too (not a great cook though)",
    "about_mod": "Very helpful very much interactive and we all can't deny the fact that how much he likes being called *SIR*\ud83d\ude06",
    "oslo_bio": "I don't know about where this house will end but we members are definitely destined to achieve greatness all of us.",
    "highradius_exp": "Definitely hectic, but it brings out my inner potential holding on to all the stress and help me in giving my best.",
    "pic": "https://drive.google.com/open?id=1x7nMwuuihdYp8IhGvMXCUlu_fBexP4qm",
    "skills": "Drawing",
    "team": "CONTENT",
    "img_link": "https://i.ibb.co/WKFcqTC/IMG-20180912-001058-097-AKRITI-DEY.jpg"
  },
  {
    "timestamp": "5/3/2020 2:22:13",
    "email": "1706048@kiit.ac.in",
    "name": "Kushal Agarwal",
    "crazy_things": "I am always sleepy, even though I can force my body to stay awake for as long as I want. I have stayed awake for about upto 50-55 hours on end when required\ud83d\ude05",
    "interests": "Reading, and consuming all forms of digital content. Also, international politics. ",
    "post_lockdown_plan": "Sleep on a real bed (There's a whole story behind this...) ",
    "insta": "",
    "more_info": "",
    "about_mod": "He is very humble, down-to-earth, and always open to helping everyone of us. ",
    "oslo_bio": "Oslo might be one of the more forgettable characters of Money Heist but we sure as hell aren't going to let that be repeated when it comes to our House at HRC. ",
    "highradius_exp": "It's been a bittersweet experience for me so far, as I am mostly a couch potato, and HRC has given me the motivation required to work hard and manage my time well for optimum efficiency. ",
    "pic": "https://drive.google.com/open?id=10v7Q4s-2lXMZGJ1_uSoJg4bgfBc2qgtX",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/1MKcyjg/IMG-20191123-204631-4-KUSHAL-AGARWAL.jpg"
  },
  {
    "timestamp": "5/3/2020 2:36:15",
    "email": "1702149@kiit.ac.in",
    "name": "Akash Tarasia",
    "crazy_things": "I use a Pizza as a plate for my burger.",
    "interests": "Netflix and Football",
    "post_lockdown_plan": "Stress about what's gonna happen next",
    "insta": "https://www.instagram.com/akash.tarasia",
    "more_info": "I like to throw around random facts: Leonardo Da Vinci is the inventor of Scissors",
    "about_mod": "Very Enthusiastic",
    "oslo_bio": "We certainly had more screentime and dialogues than Oslo.",
    "highradius_exp": "I've worked harder in the last 4 days than in my entire college life",
    "pic": "https://drive.google.com/open?id=1PKmx9eynn7eUHF7jzWJH9cJoj4gz0p_o",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/mCYD8Jz/Snapchat-581961029-02-AKASH-TARASIA.jpg"
  },
  {
    "timestamp": "5/3/2020 16:57:37",
    "email": "1705900@kiit.ac.in",
    "name": "Nidhi Bhattacherjee",
    "crazy_things": "I'm from the CSE department. I consider myself to be straightforward and just pretty easygoing. I love hearing about other people's stories. And I also obviously love to Netflix and chill.",
    "interests": "I do like sleeping but only when it's not the time to sleep! Other than that I'm a Netflix person. And I also love coming up with alternate endings to novels, movies and TV series.",
    "post_lockdown_plan": "Eat out. Without a question.",
    "insta": "",
    "more_info": "",
    "about_mod": "Hamid has got to be the most dedicated person I've ever met. He works really hard on us, which I find commendable.",
    "oslo_bio": "I think Oslo as a house is quite unique. We have the right balance of everything. We study, we make memes, we enjoy. I can't wait to get to know my fellow housemates better!",
    "highradius_exp": "My experience at HRC will be something I remember for the rest of my life. It was really eye-opening, getting to know how a corporate giant works. I am able to see a clear vision of what I want to do with my life, ever since I joined.",
    "pic": "https://drive.google.com/open?id=1k6Aq6xpLOyRomz_BMn8oFo5szQRL5AwV",
    "skills": "I am fairly good in C programming. And I also like Python a lot. Apart from this, I am capable of working in a team. And I try to practice perseverance as much as I can.",
    "team": "",
    "img_link": "https://i.ibb.co/G0yjZLH/IMG-20190602-WA0000-NIDHI-BHATTACHERJEE.jpg"
  },
  {
    "timestamp": "5/3/2020 2:49:59",
    "email": "1704243@kiit.ac.in",
    "name": "Ahana Bandyopadhyay",
    "crazy_things": "There's a crazy side that you haven't seen yet .... Mostly known for laughing  at the wrong time in the wrong places in front of wrong people!!!",
    "interests": "I love dancing... reading....  writing and a part of me lives in space!! Oh and Netflix is an organ!!!",
    "post_lockdown_plan": "Mereko lagta hai jab tak yeh lockdown khatam hoga I'll turn into a walking zombie....but I I'm still sane....  pagalo ki tarah raaste mein nikalke daurna hai mereko and phir Kiit jana hai!!! Missing my people!!",
    "insta": "https://www.instagram.com/ahanabanerjee25",
    "more_info": "There's always a story waiting to be told!",
    "about_mod": "The fact that he is always available for us....no matter what...",
    "oslo_bio": "People are always ready to clear your doubts....bhalei raat ke 2 baje ho ya phir quiz ke baad ka chotu sa free time mein bhi",
    "highradius_exp": "Indeed a roller coaster ride....but a lovely one.... eagerly waiting for the next week to unfold",
    "pic": "https://drive.google.com/open?id=1M_2sH5wJ4VEvPUt6f_2GSD7-IzCmFyoU",
    "skills": "Arduino IoT and embedded, Reading, writing, dancing, reading more about astrophysics painting",
    "team": "",
    "img_link": "https://i.ibb.co/PWFvgqT/IMG-20200202-WA0003-AHANA-BANDYOPADHYAY.jpg"
  },
  {
    "timestamp": "5/3/2020 16:58:54",
    "email": "1705597@kiit.ac.in",
    "name": "Gautam Gobind Singh",
    "crazy_things": "I am a music junkie.",
    "interests": "Netflix",
    "post_lockdown_plan": "Surly going to have momos and street foods",
    "insta": "",
    "more_info": "",
    "about_mod": "He is a enthusiastic person. Couldn't find such moderator who can explain same thing again and again.",
    "oslo_bio": "As Oslo city is know for its museums, our house Oslo will also be a museum for Highradius Internship program's with alot of memories and great collective work.",
    "highradius_exp": "It's been a very hectic but came to know I can also sit for 14-16 hrs a day . Never ever dedicated so much time for study purpose .",
    "pic": "https://drive.google.com/open?id=1kCkIaCj5wIqjsNWt6Kwq1s1Y9MiPZZlV",
    "skills": "Android development, problem solving , c,java,c++,IoT",
    "team": "",
    "img_link": "https://i.ibb.co/qdXjFVX/IMG-20200329-191217-2-GAUTAM-GOBIND-SINGH.jpg"
  },
  {
    "timestamp": "5/3/2020 17:13:27",
    "email": "1705129@kiit.ac.in",
    "name": "Ayush Kumar",
    "crazy_things": "I am very curious about craziness of everything rather than me ! ",
    "interests": "Both Sleep and Binge in equal proportions.\nBut these things are occasionally replaced by Football, Badminton and Cricket.",
    "post_lockdown_plan": "I would like to sleep because I missed sleeping under the anxiety that whole world is working except me !",
    "insta": "https://www.instagram.com/lord_ayush",
    "more_info": "F.R.I.E.N.D.S is overrated !",
    "about_mod": "I hope one day Hamid will be comfortable with everyone in House Oslo calling him SIR !",
    "oslo_bio": "If Oslo would have been the leader, we surely would not be tolerating Arturo Rom\u00e1n for 4 seasons and for the 5th as well !",
    "highradius_exp": "I will never underestimate Roller Coasters again !\nAlso I never thought that I would be opening Telegram so frequently and not for downloading movies and web series !",
    "pic": "https://drive.google.com/open?id=1azepeFb4-beeYRrLw0Onw5XGjKd_RstR",
    "skills": "C, C++, Java, Android App Development, Internet Of Things, Procrastination, Badminton.",
    "team": "",
    "img_link": "https://i.ibb.co/PQVgWkM/photo-2020-05-03-02-42-14-AYUSH-KUMAR.jpg"
  },
  {
    "timestamp": "5/3/2020 4:22:56",
    "email": "1730071@kiit.ac.in",
    "name": "Aakriti",
    "crazy_things": "I love dancing in rain on the roads. I laugh at serious situations. Whenever try remembering an answer in an exam,always ends up by remembering weird songs that goes on n on n on.. ",
    "interests": "Netflix.\nTalking,playing football with friends shoes,using straw on plate..",
    "post_lockdown_plan": "Go out and chill with family and friends",
    "insta": "https://www.instagram.com/aakriti_2103",
    "more_info": "Many a times I make fake accounts and irritate my friends.. Sometimes,fake calls too\ud83d\ude48",
    "about_mod": "Our moderator Hamid, a really kind and helpful guy. He is very supportive. Always ready to guide and such a friendly nature he possess.",
    "oslo_bio": "ELITE:-- Oslo is the best.. The members of this group are really helpful and interactive..Great team n always ready to win..Feels great to be a part of this house..OSLO\ud83d\udd25",
    "highradius_exp": "HIGHRADIUS is truly a roller coaster.. Learnt a lot and also got an idea of the corporate world.. Learned to cope up with scarcity of time and the amount of workload and stress. I learned to handle time scarcity and pressure simultaneously.  A great experience that taught life isn't that easy.. This is just the beginning. Leaned many things and looking forward to the next level with the same enthusiasm.\nMost importantly, i realised that i can spend about 8 hours without using social media.. Wow! \ud83d\ude02",
    "pic": "https://drive.google.com/open?id=1qdWvqdhyX90Nb7UkRzwQnAYU3w7_BlgB",
    "skills": "Administrative skills, Organising skills, pursued Computer courses, cooking, singing n dancing skills.",
    "team": "",
    "img_link": "https://i.ibb.co/3mbH5yk/IMG20200503002633-AAKRITI-prasad.jpg"
  },
  {
    "timestamp": "5/3/2020 17:36:35",
    "email": "1729181@kiit.ac.in",
    "name": "Swarnim Anand",
    "crazy_things": "I have the power to perform a task whole day till its completed without getting bored if I am interested in it.",
    "interests": "I like watch Netflix ,Hotstar Shows, playing Cricket or any other games in my free time.",
    "post_lockdown_plan": "I want to meet my all college friends, watching movies with them  and do lots of fun .",
    "insta": "https://www.instagram.com/swarnimanand1998",
    "more_info": "I am a Full Stack Web Developer, I have an experience of 1.75 years in Web Development. I am just waiting for phase 2 ,because phase 2 will be much interesting than phase 1 for me.   ",
    "about_mod": "He is very nice guy ,he always help us wherever we have got stuck since the first day of our summer internship.",
    "oslo_bio": "Oslo is a great team ,where everyone help each other.Our moderator is also very good.",
    "highradius_exp": "By doing this internship I am growing day by day.I don't know these things(Python,ML) which  I have  not done in last 3 years but today I have to do these things in two weeks.It was so hectic but I am trying to cop-up. ",
    "pic": "https://drive.google.com/open?id=1Ai8aIIlN-Yt7w-_9i4c17MSa3cHXb8Jq",
    "skills": "HTML,CSS,JAVASCRIPT,C,C++,Node.Js,Bootstrap,Data Structure,MongoDb",
    "team": "",
    "img_link": "https://i.ibb.co/znXRbHr/Swarnim-SWARNIM-ANAND.jpg"
  },
  {
    "timestamp": "5/3/2020 8:14:44",
    "email": "1705907@kiit.ac.in",
    "name": "Celina Rout",
    "crazy_things": "When I feel stressed I end up eating a lot!! Probably a hell lot!!",
    "interests": "Spoity and chill",
    "post_lockdown_plan": "Will try to learn and exploring more!!",
    "insta": "https://www.instagram.com/__c.e_l.i_n.a__",
    "more_info": "",
    "about_mod": "Benevolent",
    "oslo_bio": "Oslo house is amazing, like the people, the moderator, all are so helpful and active!!",
    "highradius_exp": "I won't deny that it wasn't hectic at all... Since I am habituated with it, I feel like I got lot of things to learn and do and it's always good to learn new stuffs.",
    "pic": "https://drive.google.com/open?id=178E3HKUaTVofYHRz725XzD2hv3pPTBeG",
    "skills": "",
    "team": "MEDIA",
    "img_link": "https://i.ibb.co/bdj82C2/Image-7457-CELINA-ROUT.jpg"
  },
  {
    "timestamp": "5/3/2020 9:40:40",
    "email": "1730161@kiit.ac.in",
    "name": "Harshit Gupta",
    "crazy_things": "Introvert , Foodie",
    "interests": "Sleeping",
    "post_lockdown_plan": "Go to a restaurant to eat ",
    "insta": "https://www.instagram.com/_.harsh.gupta",
    "more_info": "",
    "about_mod": "nice ",
    "oslo_bio": "We are there to suppress other house and tell them there is one king (House Oslo)",
    "highradius_exp": "A great experience",
    "pic": "https://drive.google.com/open?id=1o1Jbeo5Y07Nef800fNVBCWvWXPdgeMdY",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 9:59:47",
    "email": "1704681@kiit.ac.in",
    "name": "Sweta suman",
    "crazy_things": "I'm just an introvert ",
    "interests": "Sleeping",
    "post_lockdown_plan": "Obviously KFC",
    "insta": "",
    "more_info": "",
    "about_mod": "Patient guy",
    "oslo_bio": "Our house is most interactive one.",
    "highradius_exp": "Now I can sit for more than 13 hours a day and I have developed some skills in ml .",
    "pic": "https://drive.google.com/open?id=1uavqSV_1EkOlWgCLDNBT1ZcwQOqJAX5T",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/C1RD2wX/In-Shot-20191015-194352471-SWETA-SUMAN.jpg"
  },
  {
    "timestamp": "5/3/2020 10:03:19",
    "email": "1705909@kiit.ac.in",
    "name": "Debanjan Podder",
    "crazy_things": "1.I have travelled almost every part of India but never travelled outside my country .  2.I like to stay alone most of the times . 3.I like to irritate people when they are angry with me and make them more angry . 4.when someone give me motivational speech,I just think of those 3 words...\"Why So Serious????\" . 5.",
    "interests": "I would like to sleep 24 hours in a day but that's not possible...so in my free time I like to watch movies or tv series like stranger things , dark in Netflix and also sometime I like to design Websites",
    "post_lockdown_plan": "I would like to go to KFC and Dominos and will try every item available in their menu .",
    "insta": "https://www.instagram.com/bubun_98",
    "more_info": "",
    "about_mod": "Funny and Helpful",
    "oslo_bio": "Every member in Oslo are very ineterested to learn new things everyday and want to explore more and when anyone ask help for in Oslo , almost everyone in the group try their best to help and our moderator is also available about 12-15 hours in a day to help us.",
    "highradius_exp": "First week was great and bit of hectic but got new things to learn and also got a taste of corporate life ! Look forward to learn new things in HRC",
    "pic": "https://drive.google.com/open?id=1Vno5AjSSZO5xtKxXHAiZTEIfnFGD31-M",
    "skills": "C , C++ , Data Structure , Java , Pyhton , HTML , CSS , BOOTSTRAP4, Javascript , NodeJS , UI Designing , ReactJS , AngularJS",
    "team": "CONTENT",
    "img_link": "https://i.ibb.co/DKfW8fb/IMG-20171019-155627-Bokeh-DEBANJAN-PODDER.jpg"
  },
  {
    "timestamp": "5/3/2020 10:14:39",
    "email": "1706166@kiit.ac.in",
    "name": "SMIT KUMAR GUPTA",
    "crazy_things": "OTAKU",
    "interests": "QUIRKIEST FOOD LOVER",
    "post_lockdown_plan": "Enjoy BARBEQUE NATION",
    "insta": "",
    "more_info": "",
    "about_mod": "Angelic head",
    "oslo_bio": "United against destiny for greatness",
    "highradius_exp": "Interactive MARATHON OF WEEK DAYS TO CHASE THE FUTURE ",
    "pic": "https://drive.google.com/open?id=1MxVk5JJ4cl7zoaVD8k86CwXvRjgQWqSY",
    "skills": "",
    "team": "CONTENT",
    "img_link": "https://i.ibb.co/1nShZGC/IMG-20180711-145512-SMIT-KUMAR-GUPTA.jpg"
  },
  {
    "timestamp": "5/3/2020 10:21:28",
    "email": "1704084@kiit.ac.in",
    "name": "Abhranil",
    "crazy_things": "Mad to jump over a high please",
    "interests": "Sleeping",
    "post_lockdown_plan": "Obviously bike riding",
    "insta": "",
    "more_info": "",
    "about_mod": "Cool and helpful",
    "oslo_bio": "Capital of Norway",
    "highradius_exp": "Exiting and hectic",
    "pic": "https://drive.google.com/open?id=13s_vep_NuzZFnOU58PWbBgg9bxIkfl66",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 10:36:47",
    "email": "1705453@kiit.ac.in",
    "name": "Satyabrata Maharana",
    "crazy_things": "Absolutely waste the whole day, playing FIFA or watching movies",
    "interests": "Sleeping, playing FIFA, watching movies and TV series",
    "post_lockdown_plan": "2-3 bike rides with some of my friends",
    "insta": "",
    "more_info": "",
    "about_mod": "He is really helpful",
    "oslo_bio": "The house has really talented people and ya we are destined for greatness.",
    "highradius_exp": "Learned a lot about the subject that seemed difficult to me.",
    "pic": "https://drive.google.com/open?id=1OSuhNJz9V0g0EbOCOjPbdPxZKHVTtCHR",
    "skills": "Basic Flutter coding",
    "team": "",
    "img_link": "https://i.ibb.co/dLqq8Mk/91-93371-66586-20200503-103559-SATYABRATA-MAHARANA.jpg"
  },
  {
    "timestamp": "5/3/2020 16:56:20",
    "email": "1705347@kiit.ac.in",
    "name": "Rabina Roy",
    "crazy_things": "I like singing out loud sometimes when I am very happy and listening to my favourite songs , well I am not a party animal but definitely a party songs lover and love bollywood music ,helps me forget all my stress.Love shopping not online but ya this gives me thrill.I am a big foodie and I love fuchkas and sweets a lot cause it is one of my cheap thrills.",
    "interests": "Watching movies,tv series ,listening bollywood music,hanging out with friends and travelling.",
    "post_lockdown_plan": "Visiting my grandmother will be my first thing to do after this lockdown because I have not seen her for a long time and want to spend some time with her.",
    "insta": "",
    "more_info": "I guess we all people can request HighRadius to make every friday a fun friday like working only for half of the day and having fun for the rest of the hours like by  chatting or playing some fun games so we all be in constant touch with each other and enjoy our weekend a bit.",
    "about_mod": "You better don't call him sir.Cause he is there for us all time clearing our issues and doubts just like a friend but as a good mentor as well.",
    "oslo_bio": "Honestly I haven't watched this series yet but as a group I like Oslo.People are active,friendly and very helpful so we rock as a team.",
    "highradius_exp": "Well from the 2nd day onwards there was too much pressure but now getting familiar with corporate work culture.Its definitely a roller coaster experience.I have learnt that I can control my sleeping hours to some extent and focus on the tasks to be completed in a certain deadline by bringing the sense of responsibility within myself.",
    "pic": "https://drive.google.com/open?id=1HyAwPnuUk_znlBqC1YQ31Q1fkOusAxbP",
    "skills": "I like android app development just a beginner but love it.",
    "team": "",
    "img_link": "https://i.ibb.co/gZfcf4F/IMG-20190902-WA0012-RABINA-ROY.jpg"
  },
  {
    "timestamp": "5/3/2020 10:49:55",
    "email": "1706525@kiit.ac.in",
    "name": "Rohan Sasmal",
    "crazy_things": "I search for meaning and purpose, even in small things.",
    "interests": "Sleeping",
    "post_lockdown_plan": "Meeting college friends.",
    "insta": "https://www.instagram.com/__rohan30",
    "more_info": "",
    "about_mod": "Hamid helps lot in solving doubts.",
    "oslo_bio": "Oslo is very good house. People are very interactive here.",
    "highradius_exp": "HighWay to HighRadius provides very well organized course. I have learnt about lots of things here.",
    "pic": "https://drive.google.com/open?id=1ZtvjNLP_DY933f39xBx7OeoV1rmDKiZv",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/s3v2wCC/photo-2020-05-03-10-45-18-2-ROHAN-SASHMAL.jpg"
  },
  {
    "timestamp": "5/3/2020 11:03:34",
    "email": "1702447@kiit.ac.in",
    "name": "Nishant Kumar ",
    "crazy_things": "I\u2019m obsessed with cold drinks I can drink litres of litre of cold drink everyday ",
    "interests": "Watching  Mahabharata till now at least 10 times I have finished it ",
    "post_lockdown_plan": "Going on a road trip with friends ",
    "insta": "https://www.instagram.com/I.m.nishant.singh",
    "more_info": "",
    "about_mod": "He is a the best moderator in my opinion because when we need help or any suggestions he is always  on o zoom call or in the telegram group also to guide us ",
    "oslo_bio": "I\u2019m happy to be a part of Oslo all the fellow Interns are nice and especially our moderator is superb he is always present for help us and I enjoyed and Learned a lot of things in this house especially the house meetings so , till my overall experience was awesome ",
    "highradius_exp": "Honestly my first weak was very hectic coz python is new for me and as I\u2019m from mechanical branch and I don\u2019t have that much grip on coding that\u2019s why I\u2019m having some difficulties but I\u2019m trying my best ",
    "pic": "https://drive.google.com/open?id=1-mz36oZkGLMVgza7sERwO3bsOlD4_oiE",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/hKZBLgV/6-E2-EFA9-A-A0-E6-4-C97-8095-2-E0-B6-F21-D190-NISHANT-KUMAR.jpg"
  },
  {
    "timestamp": "5/3/2020 11:16:08",
    "email": "1705259@kiit.ac.in",
    "name": "Rishabh Mahanta",
    "crazy_things": "I would like to share a tragedy which i get to encounter every time i make new acquaintances is that people think i am a bit shy and introvert kind of guy but when i open up after getting a bit comfortable with them it always pisses them off..",
    "interests": "Reading quora, playing badminton",
    "post_lockdown_plan": "Go out for a walk maybe...",
    "insta": "",
    "more_info": "",
    "about_mod": "Very helpful and always stays up to clear doubts",
    "oslo_bio": "I am lucky to have such a group where people are really helpful to each other",
    "highradius_exp": "I learnt those things in 4 days which i was trying to  learn for 2yrs.",
    "pic": "https://drive.google.com/open?id=1ky90ouuOgoyfhG_6lWJslJxUKfeQHAiO",
    "skills": "Data science,C,C++, writing content",
    "team": "",
    "img_link": "https://i.ibb.co/1rSv3S8/IMG-20190514-WA0000-RISHABH-MAHANTA.jpg"
  },
  {
    "timestamp": "5/3/2020 11:16:13",
    "email": "1705133@kiit.ac.in",
    "name": "Chetan Anand",
    "crazy_things": "I am very approachable but i may portray that i am not ",
    "interests": "Play Football in rain ,in summer ANYTIMEE",
    "post_lockdown_plan": "Eat street food and meet my friends I miss pani puri a lot \ud83d\ude22",
    "insta": "https://www.instagram.com/_chetan10_",
    "more_info": "Ecstasy and abyss go hand in hand",
    "about_mod": "Hamid is really a great guy always helpful even after 7pm we can approach him with our doubts and he solves them",
    "oslo_bio": "I wanted to get a cool character like Tokyo or denver. I think Oslo is the PROFESSOR.Coz we the BOSS.",
    "highradius_exp": "Tiring and very knowledgeable. Learnt a lot in this lockdown which is some productive work i was aspiring to do.",
    "pic": "https://drive.google.com/open?id=1fwC7gGXxQTDMqtpzGRlbI6-c4M4MhA_4",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/9sH1MQs/IMG-20200209-205031-369-CHETAN-ANAND.jpg"
  },
  {
    "timestamp": "5/3/2020 11:29:01",
    "email": "1728179@kiit.ac.in",
    "name": "Sumitra Panda",
    "crazy_things": "Witty",
    "interests": "Stalking food bloggers on Instagram ",
    "post_lockdown_plan": "I would like to go out and quench my thirst by having some good street foods",
    "insta": "https://www.instagram.com/_s.u.m.i.t.r.a_",
    "more_info": "",
    "about_mod": "He is very motivating ",
    "oslo_bio": "As a group or house in hrc the amazing thing is the help I get from moderator as well as from fellow interns when in a problem. The roller-coaster ride wouldn't have been this much fun without them",
    "highradius_exp": "Through this internship I got to learn lots of new things in such a short span of time and the enthusiasm and the pressure that it generated was great in its own way ",
    "pic": "https://drive.google.com/open?id=158n2KgbI_2wiiXmUNLXRmIfrxRNFBzDS",
    "skills": "Ability to learn from mistakes",
    "team": "",
    "img_link": "https://i.ibb.co/HppPLdZ/IMG-20190616-103707-SUMITRA-PANDA.jpg"
  },
  {
    "timestamp": "5/3/2020 11:36:39",
    "email": "1706550@kiit.ac.in",
    "name": "Somen biswal",
    "crazy_things": "Introvert and love watching cricket videos on Youtube, I can spend hours watching them.",
    "interests": "Mostly I like to play cricket and other sports and also like to watch horror movies most of the times ",
    "post_lockdown_plan": "Go out on a bike ride with all my friends",
    "insta": "https://www.instagram.com/somen_biswal",
    "more_info": "",
    "about_mod": "Make us understand every topics with utmost ease and intrest",
    "oslo_bio": "Best group as everyone helps each other in clearing doubts or any query they face.",
    "highradius_exp": "Till now it's amazing as everything about this rollercoaster ride is new and different though the schedule is hectic still it's feels challenging and that's what motivates me to keep going . Getting to learn alot of new things with lots of effort which make this journey more interesting.",
    "pic": "https://drive.google.com/open?id=1NnhUevibshq2Qx0b-0weDVi4bNpHFs3Q",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/BPwZW65/IMG-20200110-000543-SOMEN-BISWAL.jpg"
  },
  {
    "timestamp": "5/3/2020 11:40:32",
    "email": "1728183@kiit.ac.in",
    "name": "Shubhanshu Pratap SIngh",
    "crazy_things": " i am a big time foodie, so my favorite cuisine is Mughlai, especially Tandoori Chicken & Mughlai Biryani.I mostly listen to contemporary R&B and rap music.I love motorsports and i love watching F1.Even my favourite drivers are Ayerton Senna, Michael Schumacher,Lewis Hamilton & Sebastian Vettel",
    "interests": "Netflix,sketching & painting",
    "post_lockdown_plan": "I would like to go to my favorite restaurants and munch on my favorite dishes ",
    "insta": "https://www.instagram.com/tsar_king18",
    "more_info": "I love to go on long rides alone.(especially without my mobile phone)",
    "about_mod": "Our moderator is an awesome chap, very helpful too indeed.",
    "oslo_bio": "Oslo was known for his brute force. Even though he died but is always remembered and missed by everyone.",
    "highradius_exp": "I had an awesome experience at HighWay to HighRadius so far. After my JEE preparations, I have never worked & studied, for more than 10 hours at a stretch.So it brought me back those days. LOL",
    "pic": "https://drive.google.com/open?id=1Ba1hDZZDtEqMD0RC7FbRo-LCTc20P6z_",
    "skills": "Project management, analysis, problem solving, adaptability, organizational skills, Cooperative and lastly a good listener",
    "team": "",
    "img_link": "https://i.ibb.co/LSSd6dz/IMG-20181019-222215-SHUBHANSHU-PRATAP-SINGH.jpg"
  },
  {
    "timestamp": "5/3/2020 21:05:40",
    "email": "1705694@kiit.ac.in",
    "name": "Disha Kar",
    "crazy_things": "A good listener, Talkative, Biryani Lover",
    "interests": "Quirkiest interests are forever Eating iand Graphic Designing. Even after a tiring day, designing makes me feel alive! Being a foodie, i also have a thing for cooking. I love experimenting with new cuisines. ",
    "post_lockdown_plan": "Rush to my hostel and get my things back. Half of my life is still back there. :(",
    "insta": "https://www.instagram.com/di_sha_kar",
    "more_info": "Am really happy to meet so many different people. Although virtually, but yeah, happy and proud to be a part of House Oslo.",
    "about_mod": "Very Helpful and Very Cool",
    "oslo_bio": "Yaar money heist ka koi idea nai hai. :{\nBut I have full faith on our House Oslo. And will do great \u2605",
    "highradius_exp": "I have been able to do things which I never thought I would do. This lockdown had brought out my laziest form ever. But when Highway to highradius started I was on my toes all the time. I have been pushing myself to my greatest limits. Also coming to the technical part, I was always intimidated with machine learning. But thanks to Hrc, they made me realise that this roller coaster, isn't for everyone, But if i have the will to do something, i can surely ride it. ",
    "pic": "https://drive.google.com/open?id=1O7jBGZ_O7PhhLo2MBF0SWd2z9YluX_ai",
    "skills": "Leadership, Adaptive, Pressure Performance, Creative Problem Solving",
    "team": "MEDIA",
    "img_link": "https://i.ibb.co/4FgjCh0/IMG-20200107-110134-01-DISHA-KAR.jpg"
  },
  {
    "timestamp": "5/3/2020 19:47:38",
    "email": "1730073@kiit.ac.in",
    "name": "Adarsh Kumar singh",
    "crazy_things": "I am so hilarious that i m the only one who gets my jokes\ud83d\ude02 . Also sometimes i and my friends ofcourse wish that my mouth had a pause button.",
    "interests": "Netflix\nQuirkiest interest- time travelling",
    "post_lockdown_plan": "The first thing i would do is eat biryani",
    "insta": "https://www.instagram.com/adarshadtp97",
    "more_info": "",
    "about_mod": "We are lucky to have such an understanding moderator.",
    "oslo_bio": "House Oslo is destined for some next level  greatness although oslo died in the very first season of money heist",
    "highradius_exp": "The first week was really hectic but gradually i am now getting used to this.",
    "pic": "https://drive.google.com/open?id=1j7HNUHso2A6mKy--3qZbqmNZi_5RqAyd",
    "skills": "1. Web developer\n2. Coder\n3. Csgo gamer",
    "team": "",
    "img_link": "https://i.ibb.co/9r8LGxq/SAVE-20190322-234256-ADARSH-KUMAR-SINGH.jpg"
  },
  {
    "timestamp": "5/3/2020 17:06:46",
    "email": "1703200@kiit.ac.in",
    "name": "Gourav Bhattacharjee",
    "crazy_things": "I simply stand and watch an ongoing fight. BOOM, the very next moment I am somehow into that fight. Also, I predicted the future and started practising social distancing with my friends just about a month before it became the trend. Amazing, isn't it?",
    "interests": "1) I love keeping myself engaged in a flight simulator all day long!\n2) Binge Watching obviously, who doesn't?",
    "post_lockdown_plan": "Stop cancelling those amazing plans at the last moment and take that amazing road trip all the way to Bhutan! <3",
    "insta": "https://www.instagram.com/vt_grx",
    "more_info": "",
    "about_mod": "Hamid is a great guy. He is supportive and looks after all the issues his house is going through. Always keep \"interact\"ing, Hamid! :P",
    "oslo_bio": "\"Jhund meh toh suar aate hai, sher akela hi aata hai\". Oslo does not need any description. Oslo is the description. #BB",
    "highradius_exp": "1) My first objective was to find out more about Oslo xD.\n2) Being a tech guy, how can you survive without saying \"Yaar ye Biz waale kya lucky hai yaar. Art & Craft chal raha hai inka\" atleast thrice a day?\n3) From \"yaar time pass hi nahi ho paa raha\" to \"yaar koi roko inn sab ko, time hi nahi mil raha\", we somehow became a part of High Radius!",
    "pic": "https://drive.google.com/open?id=15g6-mAhmrSMjYUZfyZJLP8b5qlRLT-2m",
    "skills": "1) Photography and Post Processing\n2) Gaming and Simulation\n3) Messing with electronic items\n4) A little bit of coding\n5) Commercial Aviation and Drones.",
    "team": "",
    "img_link": "https://i.ibb.co/5194fp4/Snapchat-1203146956-GOURAV-BHATTACHARJEE.jpg"
  },
  {
    "timestamp": "5/3/2020 11:59:48",
    "email": "1706473@kiit.ac.in",
    "name": "Varshini Ambati ",
    "crazy_things": "I am very good at lazying around ",
    "interests": "Sleeping, eating new cuisines, reading mythology and watching movies ",
    "post_lockdown_plan": "Eat golgappas and momos ",
    "insta": "https://www.instagram.com/Varshini_Ambati ",
    "more_info": "",
    "about_mod": "Very Helpful ",
    "oslo_bio": "A source of great enthusiasm  and information ",
    "highradius_exp": "At first it was very hectic but still trying to get into the roller coaster. It has made me my quarantine life productive. ",
    "pic": "https://drive.google.com/open?id=1yfMU5BobJHZGihJnuoRoy6QAOUx2ms_6",
    "skills": "Art and craft, passionate about cooking",
    "team": "",
    "img_link": "https://i.ibb.co/rHXmn98/IMG20200117153654-VARSHINI-AMBATI.jpg"
  },
  {
    "timestamp": "5/3/2020 11:58:31",
    "email": "1729111@kiit.ac.in",
    "name": "Anusha Bhowmick",
    "crazy_things": "Candid",
    "interests": "Reading books, painting, binge watching Netflix",
    "post_lockdown_plan": "Eat a whole pizza",
    "insta": "https://www.instagram.com/anushabhowmick",
    "more_info": "A happy-go-lucky person who looks at the world as a glass always half full",
    "about_mod": "He's very approachable",
    "oslo_bio": "I do hope we don't end up like him at the end of this internship!\ud83d\ude02",
    "highradius_exp": "Although exhausting,this internship is very fulfilling and at the end of the day I'm always happy to have had a productive day and no regrets of wasting time. One thing I realised after joining is that there are far more hours in a day, and a lot you can accomplish in a day than I thought was possible before.",
    "pic": "https://drive.google.com/open?id=1DMMD8OMiVkPC9tJyjfGXbAnLe5rVzp2J",
    "skills": " c,c++, python,data structures,ml, painting,singing,debating",
    "team": "",
    "img_link": "https://i.ibb.co/RQvSYyj/IMG-20190414-WA0009-ANUSHA-BHOWMICK.jpg"
  },
  {
    "timestamp": "5/3/2020 17:13:44",
    "email": "1705658@kiit.ac.in",
    "name": "Surya Kant",
    "crazy_things": "I wish to die driving my BMW at a speed above 250\ud83d\ude02",
    "interests": "Sleeping",
    "post_lockdown_plan": "Chai sutta with friends at college",
    "insta": "https://www.instagram.com/kantsurya556",
    "more_info": "",
    "about_mod": "Cool and understanding",
    "oslo_bio": "We will  perform way better than money heist in real life",
    "highradius_exp": "Before highway to highradius i used to sleep 12-14 hours now i hardly sleep 8hours",
    "pic": "https://drive.google.com/open?id=1lW8Vz0vVvBll3v-OE-xBL9iaU8itoIUf",
    "skills": "Good problem solving skills.\nFast learner.",
    "team": "CONTENT",
    "img_link": "https://i.ibb.co/tmqVxMm/IMG-20180927-134750-365-SURYA-KANT.jpg"
  },
  {
    "timestamp": "5/3/2020 12:14:36",
    "email": "1728273@kiit.ac.in",
    "name": "Aindril kar",
    "crazy_things": "Interested to have a meetup with a real ghost,Crazy about cars as my surname suggests,Dog lover.",
    "interests": "Telegram as it has channels that provide free netflix contenst.....other than that i like photography,Mobile Chipsets,Music",
    "post_lockdown_plan": "Get me a Redbull....a die hard fan of Redbull and ofcourse check on my friends who all are yet to die.",
    "insta": "https://www.instagram.com/el.profesor_kar",
    "more_info": "\"Una mattina mi son alzato\"",
    "about_mod": "Friend",
    "oslo_bio": "Oslo died as a hero and will live as one",
    "highradius_exp": "Dedication,Became Organized.",
    "pic": "https://drive.google.com/open?id=16oE567RgX5uKnfPcbJGY3DG2Zg03pixK",
    "skills": "",
    "team": "MEDIA",
    "img_link": "https://i.ibb.co/4MKKtCv/Kar-Aindril.jpg"
  },
  {
    "timestamp": "5/3/2020 17:30:04",
    "email": "1705016@kiit.ac.in",
    "name": "Amisha Patel",
    "crazy_things": "Sane",
    "interests": "Sleeping",
    "post_lockdown_plan": "Got out for lunch with friends",
    "insta": "",
    "more_info": "",
    "about_mod": "He is very helpful.",
    "oslo_bio": "Working great as a team.",
    "highradius_exp": "Learned a lot in past few days and got a real world experience.\n",
    "pic": "https://drive.google.com/open?id=1AKQek3DdpmOrHAIoORHGENIeBtqCNuuv",
    "skills": "Technical skills:\nProgramming languages- C , C++,JAVA, Python\n\nWeb- HTML, CSS, JavaScript, Vue.js, Vuetify\n\nData structure and algorithms\n\nSoft skills:\nProblem solving, Critical thinking, Adaptability, Collaboration",
    "team": "",
    "img_link": "https://i.ibb.co/cckR8rr/IMG-20200503-120209-AMISHA-PATEL.jpg"
  },
  {
    "timestamp": "5/3/2020 12:20:04",
    "email": "1705467@kiit.ac.in",
    "name": "Sreeja Sarkar",
    "crazy_things": "Can go on watching cartoons the entire day without a break...Likes trying out new recipes which later turns out disasterous.",
    "interests": "Draw cartoon characters",
    "post_lockdown_plan": "Rush to a restaurant..Missing Biriyani",
    "insta": "https://www.instagram.com/sreejasarkar2017",
    "more_info": "",
    "about_mod": "He encourages us to interact ",
    "oslo_bio": "Oslo is born to defeat others",
    "highradius_exp": "At the end of the day,I feel satisfied thinking that I had a productive day",
    "pic": "https://drive.google.com/open?id=1kyvuw11rmwP2v9DPnlhez4fPSvmNIWQz",
    "skills": "C,C++, Basic Java, Android, and drawing animated characters",
    "team": "",
    "img_link": "https://i.ibb.co/2yftTBz/IMG-20190120-105007-SREEJA-SARKAR.jpg"
  },
  {
    "timestamp": "5/3/2020 13:01:26",
    "email": "1728120@kiit.ac.in",
    "name": "Annie Olivia Miranda ",
    "crazy_things": "Love to explore new places and  try my hands on different musical instruments. ",
    "interests": "I'm really into landscape photography and editing. ",
    "post_lockdown_plan": "Would like to go on a hiking trip with my family. ",
    "insta": "https://www.instagram.com/annie_olivia_miranda",
    "more_info": "",
    "about_mod": "I really appreciate  the effort he puts in to lead our team by providing one-on-one guidance and support especially by conducting zoom meetings. ",
    "oslo_bio": "The group members of this team are really helpful and they try their best to help each other out with their doubts. ",
    "highradius_exp": "I never knew I had this in me to grasp so much in such a short time span. In the beginning it seemed hectic but very soon got adjusted to this routine. I feel I am ready for another steep slope in this rollercoaster ride.",
    "pic": "https://drive.google.com/open?id=1ZZ4s3IFjsUcJSkXFuwlPbNQJpwIkFetc",
    "skills": "",
    "team": "",
    "img_link": "https://i.ibb.co/Jv98dd2/SAVE-20200503-122935-ANNIE-OLIVIA-MIRANDA.jpg"
  },
  {
    "timestamp": "5/3/2020 13:17:31",
    "email": "1705281@kiit.ac.in",
    "name": "Trilok Bhattacharya",
    "crazy_things": "I get super excited by complex, quirky problems (which others find nerve-wracking) and equally enthralled by their solutions.",
    "interests": "There's no blue that a good cup of Irani chai, a nice nap, deep, intelligent conversations, and good artwork can't cure.",
    "post_lockdown_plan": "Well, lockdown is not equivalent to the end of the pandemic, so stay home till the pandemic ends and then, after all is safe, I would love to treat myself to something cheesy.",
    "insta": "https://www.instagram.com/triii_10",
    "more_info": "There's a thing about me that I hold too much pride upon, yet I do not underestimate. (P.S. That's my CGPA, which I'm definitely not going to share ;) )",
    "about_mod": "I haven't seen a more hardworking and patient person, who is always ready to help us even in the smallest of the matters.",
    "oslo_bio": "I haven't watched Money Heist, but I can surely say that in our universe of HighWay to HighRadius-Heist, we are here for a long long time and we are here to dominate. :)",
    "highradius_exp": "I have definitely been tired, but that takes a second position when I think back on how much I've learned.",
    "pic": "https://drive.google.com/open?id=1jkMT4hOrOw-xFPXlCEIEZ8C9hv5cS3_j",
    "skills": "Algorithm and DS, Solving Problems, C/C++, Python, Drawing, Sketching,  Swimming",
    "team": "CONTENT",
    "img_link": "https://i.ibb.co/vcQQ4GW/dp-Trilok-Bhattacharya.jpg"
  },
  {
    "timestamp": "5/3/2020 17:10:21",
    "email": "1704214@kiit.ac.in",
    "name": "Sayan Karmakar",
    "crazy_things": "Tech enthusiast... Foodie... Electronics freak...",
    "interests": "Sleeping(vital).. Content writing.. Watching Movies..",
    "post_lockdown_plan": "Rush to the side roads and alleys and have fast foods. Eat. Enjoy. Repeat.",
    "insta": "",
    "more_info": "",
    "about_mod": "Cool",
    "oslo_bio": "Long way to go !",
    "highradius_exp": "Learning new concepts each day. Totally new into these domain and fields. Finding hard to cope sometimes but really enjoying the roller coaster !",
    "pic": "https://drive.google.com/open?id=1XykVt1Vs95e82sa_4J67LTmqg208Byh-",
    "skills": "IOT Enthusiast, Embedded Systems, Computer Networks, Advanced Telecommunication, Cloud Computing.",
    "team": "",
    "img_link": "https://i.ibb.co/4MvYNN2/IMG-0135-SAYAN-KARMAKAR.jpg"
  },
  {
    "timestamp": "5/3/2020 17:15:01",
    "email": "1704177@kiit.ac.in",
    "name": "Atanu Saha",
    "crazy_things": "Lazy, food lover, love to travel ",
    "interests": "Eat, Sleep, movies/series, pubg, repeat",
    "post_lockdown_plan": "Gonna spend most of the time outside, roaming around",
    "insta": "",
    "more_info": "",
    "about_mod": "Serious, knows about his job pretty well, helpful. ",
    "oslo_bio": "Full of enthusiasm, a family. ",
    "highradius_exp": "A bit hectic schedule, trying to cope up with it, then came assignments and quiz, started studying more in this past week. ",
    "pic": "https://drive.google.com/open?id=1dhKYN8HnYu0OkfIyGjABBDZD7Kar40YM",
    "skills": "Python, Machine Learning, Data Science, Big Data and Hadoop, R programming, Sql, Mongo DB, Cloud Computing",
    "team": "",
    "img_link": "https://i.ibb.co/m5kD3wR/img1587508706221-ATANU-SAHA.jpg"
  },
  {
    "timestamp": "5/3/2020 17:23:51",
    "email": "1705339@kiit.ac.in",
    "name": "Nisha Sen",
    "crazy_things": "Can dance with crazy moves in any song",
    "interests": "Searching whole family tree, connections about big celebrities and also Netflix",
    "post_lockdown_plan": "Eat lots of cheesy food and Street food",
    "insta": "https://www.instagram.com/n.i.s.h.a.s.e.n",
    "more_info": "",
    "about_mod": "Very helpful",
    "oslo_bio": "We are going to achieve and win surely",
    "highradius_exp": "The first week, a full of roller coaster ride , I didn't knew I could sit in front of the laptop working on something the whole day. Thank you highway for making me realize this. I have learnt a lot new things and waiting to learn more.",
    "pic": "https://drive.google.com/open?id=1xos9_lVAfOLSLgGXfNx-v4DsBZmgKRnv",
    "skills": "Crafting and painting (colouring and fabrication mostly)",
    "team": "",
    "img_link": "https://i.ibb.co/v3KDB7W/MVIMG-20191123-113429-NISHA-SEN.jpg"
  },
  {
    "timestamp": "5/3/2020 19:37:52",
    "email": "1706302@kiit.ac.in",
    "name": "Arkadip Jana",
    "crazy_things": "Watching an intense match",
    "interests": "Fond of eating and photography and exploring more of India",
    "post_lockdown_plan": "Go for a Tour",
    "insta": "https://www.instagram.com/photogenic_aj",
    "more_info": "",
    "about_mod": "He certainly deserves a credit,as he always helps us when we are stuck at any point of time.",
    "oslo_bio": "Oslo as group is very supportive.Each and every person tries to clear each other doubts.",
    "highradius_exp": "It's a roller coaster,never though I could learn so much things this early.Hope to learn more and carry forward with HighRadius",
    "pic": "https://drive.google.com/open?id=1UiFrNjvz8JzWo7S3yQhqeA88Ymz3hPZU",
    "skills": "C++,Java,Android Application,Photography Editing",
    "team": "",
    "img_link": "https://i.ibb.co/MDGgkRw/1706302-ARKADIP-JANA.jpg"
  },
  {
    "timestamp": "5/3/2020 17:34:30",
    "email": "1728154@kiit.ac.in",
    "name": "Chirag garg",
    "crazy_things": "Fifa camp",
    "interests": "Sleeping",
    "post_lockdown_plan": "Playing cricket",
    "insta": "",
    "more_info": "",
    "about_mod": "Nice",
    "oslo_bio": "Great house",
    "highradius_exp": "Challenging",
    "pic": "https://drive.google.com/open?id=16qmVXbKf4imOGSTWXDWKsSKYiU16nd-b",
    "skills": "Microsoft ppt,word, c,c++,java",
    "team": "",
    "img_link": "https://i.ibb.co/d2y6cVv/IMG-20190531-124015-CHIRAG-GARG.jpg"
  },
  {
    "timestamp": "5/3/2020 17:39:25",
    "email": "1729051@kiit.ac.in",
    "name": "Ria",
    "crazy_things": ".",
    "interests": "I love watching movies on Netflix.",
    "post_lockdown_plan": "Shopping",
    "insta": "https://www.instagram.com/_ria_k_",
    "more_info": "",
    "about_mod": "Subject-matter expert",
    "oslo_bio": ".",
    "highradius_exp": "This first week has really been a roller coaster ride for me but it was an awesome experience.",
    "pic": "https://drive.google.com/open?id=1fzYZtwA891d4nEkYu9gGDg8ug2cP-9IY",
    "skills": "Web development and cyber security",
    "team": "WEB",
    "img_link": "https://i.ibb.co/BBhCTDJ/IMG-20200501-220041-709-Ria.jpg"
  },
  {
    "timestamp": "5/3/2020 17:56:14",
    "email": "1704135@kiit.ac.in",
    "name": "Shashank Kumar",
    "crazy_things": "I m either super lazy or super active",
    "interests": "Watching south indian hindi dubbed movies on youtube",
    "post_lockdown_plan": "Hit the Gym",
    "insta": "https://www.instagram.com/shashank_singh_shishodia",
    "more_info": "",
    "about_mod": "He must be fade up of answering same doubts again and again\ud83e\udd23",
    "oslo_bio": "Havent watched",
    "highradius_exp": "I am surprised that even i can follow a tight schedule",
    "pic": "https://drive.google.com/open?id=1toQKFH321_iiOZlnbHk2oivKXmrHKVb6",
    "skills": "I am great at cooking and Cricket",
    "team": "",
    "img_link": "https://i.ibb.co/zNY8L5z/00-B0-C479-81-C6-4-EF7-A567-A1-FBC81-D841-F-SHASHANK-KUMAR.jpg"
  },
  {
    "timestamp": "5/3/2020 18:25:32",
    "email": "1705475@kiit.ac.in",
    "name": "Vipul prakah",
    "crazy_things": "I want to win at all cost.",
    "interests": "Sleeping and scoring more and more goals in fifa",
    "post_lockdown_plan": "Eating chilli potato at red chillies",
    "insta": "https://www.instagram.com/royvipul3",
    "more_info": "If i don't win, the game is'nt over yet",
    "about_mod": "Helpful",
    "oslo_bio": "We will make others perish",
    "highradius_exp": "Earlier i used to study a few hours,but after joining highradius i discovered my true potential,now i make 10times more out of a single day as compared to previous.",
    "pic": "https://drive.google.com/open?id=10Jx7hF5jMu1Jqc1ZpPVhchXCIZi1MiUi",
    "skills": "C,java,basic dsa, programming,html,css teaching,through ball expert in fifa,out of box goals expert in fifa.",
    "team": "",
    "img_link": "https://i.ibb.co/HP8SSP4/F2640-VIPUL-PRAKASH.jpg"
  },
  {
    "timestamp": "5/3/2020 18:44:06",
    "email": "1705008@kiit.ac.in",
    "name": "Aditya",
    "crazy_things": "can play games for 16 hrs a day",
    "interests": "gaming",
    "post_lockdown_plan": "meet with freinds",
    "insta": "https://www.instagram.com/__adit_ya__",
    "more_info": "",
    "about_mod": "he is a nice guy and is very helpful.",
    "oslo_bio": "house is very active . everybody takes part in the conversations. ",
    "highradius_exp": "experience so far was exactly like a roller coaster ride. Noticed i can sit in front of pc for straight 12 hrs while i am not gaming",
    "pic": "https://drive.google.com/open?id=1HyDQodS3ICac8RW30_gPsQEZtPZNOfFZ",
    "skills": "coding, gaming",
    "team": "",
    "img_link": "https://i.ibb.co/nbG8Z57/IMG-20200503-183531-ADITYA.jpg"
  },
  {
    "timestamp": "5/3/2020 18:57:46",
    "email": "1706323@kiit.ac.in",
    "name": "Hanee Rai",
    "crazy_things": "I love representing fashion at every opportunity I get and that makes me feel more of myself because to me fashion is something that represents my identity.",
    "interests": "I love reading novels and writing some creative contents based on my personal experience.",
    "post_lockdown_plan": "I will probably go for an outdoor shoot.",
    "insta": "https://www.instagram.com/haneerai",
    "more_info": "",
    "about_mod": "Hamid is just so caring and responsible at the same time.Always comes up to rescue whenever in need.",
    "oslo_bio": "People in this house are really creative and exchange a positive environment with each other ,this is what makes it unique.",
    "highradius_exp": "This has been really challenging to me but the most important thing I learned from this is that I got to know about time management skills as I really lacked it.So apart from gaining knowledge,it's really helpful for my personal growth as well.",
    "pic": "https://drive.google.com/open?id=1QnSypwKOS8m9W-kbz-VWk04ENReTZZKV",
    "skills": "Reading,dancing,singing,modelling.",
    "team": "",
    "img_link": "https://i.ibb.co/jrz2RrS/DSC03949-01-HANEE-RAI.jpg"
  },
  {
    "timestamp": "5/3/2020 19:18:35",
    "email": "1705143@kiit.ac.in",
    "name": "Kaustav Ghosh",
    "crazy_things": " I'm afraid with anything related to eyes!",
    "interests": "Netfilx, Gordon Ramsay,anime,movies,and playing my favourite moba dota 2",
    "post_lockdown_plan": "Hang out with friends and complete the plans made before lockdown",
    "insta": "https://www.instagram.com/Kaustavred",
    "more_info": "",
    "about_mod": "Hamid is good at handling the group , does nt do or say unnecessary stuffs , helps and guides us by finding time in his daily schedule. What better moderator cud we ask for!!",
    "oslo_bio": "Oslo is a very interactive group. Always some discussion going on which makes me feel the need to participate in the discussions and to leaving everything at hand and put more effort in hiradius assignments and hands ons",
    "highradius_exp": "I never sat for so long in place to code ... Now the scenario is i am always busy coding and gaining knowledge . Changed my outlook to industry in a positive way.",
    "pic": "https://drive.google.com/open?id=1CtXI7P08tfi4TsWV8bSL7feuOunmn4Em",
    "skills": "C,c++",
    "team": "",
    "img_link": "https://i.ibb.co/ck3ZG3W/IMG20200415185148-KAUSTAV-GHOSH.jpg"
  },
  {
    "timestamp": "5/3/2020 19:27:12",
    "email": "1706144@kiit.ac.in",
    "name": "Prawal Mishra",
    "crazy_things": "Cry like a baby",
    "interests": "Painting, Sketching, Gaming, Basketball",
    "post_lockdown_plan": "Chicken Leg Piece",
    "insta": "https://www.instagram.com/baadshah_bawal",
    "more_info": "",
    "about_mod": "Very helpful and patient when it comes to clearing the doubts.",
    "oslo_bio": "I couldn't have asked for a better House to be in, cause WE ARE THE BEST!!",
    "highradius_exp": "Never thought I would learn so much in this short period of time and make such crazy good friends!",
    "pic": "https://drive.google.com/open?id=1YEB6ham3pxdxpm2EmSBj1pN5aSdl1r7V",
    "skills": "Cloud Computing, AWS, Front End Development, Industrial IoT, Python & JAVA(DS & Algorithms), Linux, RDBMS(SQL), Android Studio, Github",
    "team": "",
    "img_link": "https://i.ibb.co/HFrVcvm/prawal.jpg"
  },
  {
    "timestamp": "5/3/2020 19:45:16",
    "email": "1705094@kiit.ac.in",
    "name": "Vineet Kumar Gupta",
    "crazy_things": "Determined, Enthusiastic and a learner.",
    "interests": "I code. I like to manage and sort things. I like to help people when I can.",
    "post_lockdown_plan": "Go for a long ride.",
    "insta": "",
    "more_info": "",
    "about_mod": "Hamid is kind and hardworking.",
    "oslo_bio": "House Oslo is House Stark of Winterfell",
    "highradius_exp": "I learnt to sir and work. I learnt to find joy in hardwork. I learnt about my inner capabilities.",
    "pic": "https://drive.google.com/open?id=1sHtHSrcrN0nUVi2WMShDyJHzpqEgT1qI",
    "skills": "Ml, Android app development. Management.",
    "team": "",
    "img_link": "https://i.ibb.co/h2G4F1W/IMG-20200503-WA0001-VINEET-KUMAR-GUPTA.jpg"
  },
  {
    "timestamp": "5/3/2020 19:51:11",
    "email": "1705649@kiit.ac.in",
    "name": "Sreyas Panda",
    "crazy_things": "I m the laziest person so lazy to remember things about me",
    "interests": "mobile gaming, sleeping",
    "post_lockdown_plan": "I don't know",
    "insta": "",
    "more_info": "",
    "about_mod": "He is funny",
    "oslo_bio": "I don't even know that character",
    "highradius_exp": "good ",
    "pic": "https://drive.google.com/open?id=1KlrstnchD_BWMiRLADYAfCTrG5S34FJ2",
    "skills": "Have a lot of patience",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 20:06:13",
    "email": "1729179@kiit.ac.in",
    "name": "Sumit Verma",
    "crazy_things": "I speak a lot and do funny mistakes for which I am always punished. I am subject to be laughed on many times.",
    "interests": "Sleeping and roaming around with friends. ",
    "post_lockdown_plan": "Roam the city. ",
    "insta": "https://www.instagram.com/i.am.timusamrev",
    "more_info": "",
    "about_mod": "Don't address me \"sir\". please.. ",
    "oslo_bio": "We can do anything if we be together. Unity is strength. ",
    "highradius_exp": "It was indeed a roller coaster for me. ",
    "pic": "https://drive.google.com/open?id=1KtcdaU4Db0CQpQKzU2dI-0mcdo5-kApq",
    "skills": "I am good at writing. ",
    "team": "",
    "img_link": "https://i.ibb.co/7YwQxrQ/IMG-20200330-213000-SUMIT-VERMA.jpg"
  },
  {
    "timestamp": "5/3/2020 20:39:56",
    "email": "1705457@kiit.ac.in",
    "name": "Shashank sirmour",
    "crazy_things": "NaN",
    "interests": "Netflix",
    "post_lockdown_plan": "Go out",
    "insta": "https://www.instagram.com/ShashankSIRMOUR",
    "more_info": "NaN",
    "about_mod": "Very informative and nice person",
    "oslo_bio": "Alway help other",
    "highradius_exp": "I stop taking bath",
    "pic": "https://drive.google.com/open?id=1KZG6b_lOAo1u2kb49IIrPu5Sv6h8e88t",
    "skills": "Devlopment",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 20:53:11",
    "email": "1705243@kiit.ac.in",
    "name": "Manvik B Nanda",
    "crazy_things": "Extremely Sporty and somehow never gives up...",
    "interests": "Playing chess - I know very nerd type....",
    "post_lockdown_plan": "Go play Tennis ",
    "insta": "NA",
    "more_info": "Keep life simple and straight...",
    "about_mod": "Apart from many things i think the most that stood out for me was his commitment towards his men-tees, as said a leader guides the way...",
    "oslo_bio": "Glad to be part of a group that is so interactive and always ready to help each other...",
    "highradius_exp": "I have become more disciplined and have learned to push my self like never before.",
    "pic": "https://drive.google.com/open?id=1bo2lyV7uUPiyjo4f-aLobrm7NXPn2ZQS",
    "skills": "Excellent at Chess",
    "team": "",
    "img_link": "https://i.ibb.co/QdbvzGy/23244506-749430501921437-5787400657366751245-n-MANVIK-B-NANDA.jpg"
  },
  {
    "timestamp": "5/3/2020 20:55:24",
    "email": "1705138@kiit.ac.in",
    "name": "Harshit Dang",
    "crazy_things": "Can't think of any. Perhaps, I'm not crazy.",
    "interests": "Finding and watching top rated movies. Sometimes I like to watch historical documentaries.",
    "post_lockdown_plan": "Probably go to someplace nice with my loved ones.",
    "insta": "https://www.instagram.com/dangii_98",
    "more_info": "",
    "about_mod": "Hamid is a really helpful senior. He is always ready and available to help us with anything we need.  In all honesty, we are very lucky to have him as our moderator. ",
    "oslo_bio": "I haven't really watched Money Heist yet, but I've been planning on watching it for a long time. So, thank you for giving me that spoiler. :)\nBut jokes apart, we have some really exciting and talented individuals in this house. I hope that together we can learn a lot.",
    "highradius_exp": "\"The beginnings are the toughest\". Same goes for my highradius experience. A sudden wave of workload had made me lose my footing. But with the passing days, I've realised that instead of stressing out, I am very much capable of finding my feet and enjoying the tides. ",
    "pic": "https://drive.google.com/open?id=1i2oZ25rpue4WNYFrB1gBcGsh130zDixr",
    "skills": "An above average speaker, I suppose. I knew a little bit of Machine learning(also certified by Stanford - coursera) even before joining Highradius. Could be a skill, one that can probably help my case. ;)",
    "team": "",
    "img_link": "https://i.ibb.co/58nxHp6/IMG-5341-HARSHIT-DANG.jpg"
  },
  {
    "timestamp": "5/3/2020 21:12:09",
    "email": "1730202@kiit.ac.in",
    "name": "Tisa Nayak",
    "crazy_things": "I am not crazy, but I like traveling alone, being alone, and that's a crazy thing in this world. Because who likes being alone?",
    "interests": "Both. It's like Joey being asked whether he likes food more than girls.",
    "post_lockdown_plan": "Biriyani khayenge.",
    "insta": "https://www.instagram.com/tisanayak",
    "more_info": "",
    "about_mod": "Nahi pata.",
    "oslo_bio": "Oslo was the first one to die in the series. Or was it Moscow? Don't remember because both were not important characters. But I hope that we change the meaning of Oslo. We'll do better than the thing we were named after.",
    "highradius_exp": "I am sleep deprived, lekin when I can run a code successfully, it is really satisfying.",
    "pic": "https://drive.google.com/open?id=1zhghaAdmdxU0GaCqj3vdm3mo-sXaIuyu",
    "skills": "I am good at C. Other than that I am a living database containing information about most of the movies and series directed.",
    "team": "",
    "img_link": "https://i.ibb.co/7vNbkT9/5710607-0.jpg"
  },
  {
    "timestamp": "5/3/2020 21:14:18",
    "email": "1704360@kiit.ac.in",
    "name": "Lavesh Gaurav ",
    "crazy_things": "I can sit silent for hours, and its not everyone's cup of tea. ",
    "interests": "Netflix and chill.",
    "post_lockdown_plan": "Long Drive ",
    "insta": "https://www.instagram.com/gaurav_lavesh",
    "more_info": "",
    "about_mod": "Calm and composed. ",
    "oslo_bio": "His ending in the series could have been much better.",
    "highradius_exp": "Ability to sit for hours without break increased. ",
    "pic": "https://drive.google.com/open?id=1E6G8CrvNIRXfK9wnWoHaPLYw1BBcv9Ta",
    "skills": "Photography, Photo Editing, UI Design. ",
    "team": "",
    "img_link": "https://i.ibb.co/GH68mjc/LRM-EXPORT-2319469425829-20181016-222002107-LAVESH-GAURAV.jpg"
  }
]